[package]
name = "tern-imap"
description = "IMAP backend for Tern"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-imap.workspace = true
async-trait.workspace = true
chrono.workspace = true
futures.workspace = true
rustls.workspace = true
rustls-native-certs.workspace = true
tern-core.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
